export const regionData = {
  seoul: {
    name: "서울특별시",
    districts: {
      jongno: {
        name: "종로구",
        neighborhoods: [
          "청운효자동",
          "사직동",
          "삼청동",
          "부암동",
          "평창동",
          "무악동",
          "교남동",
          "가회동",
          "종로1·2·3·4가동",
          "종로5·6가동",
          "이화동",
          "창신동",
          "숭인동",
        ],
      },
      jung: {
        name: "중구",
        neighborhoods: [
          "소공동",
          "회현동",
          "명동",
          "필동",
          "장충동",
          "광희동",
          "을지로동",
          "신당동",
          "다산동",
          "약수동",
          "청구동",
          "동화동",
        ],
      },
      yongsan: {
        name: "용산구",
        neighborhoods: [
          "후암동",
          "용산2가동",
          "남영동",
          "청파동",
          "원효로동",
          "효창동",
          "용문동",
          "한강로동",
          "이촌동",
          "이태원동",
          "한남동",
          "서빙고동",
          "보광동",
        ],
      },
      seongdong: {
        name: "성동구",
        neighborhoods: [
          "왕십리2동",
          "왕십리도선동",
          "마장동",
          "사근동",
          "행당동",
          "응봉동",
          "금호1가동",
          "금호2·3가동",
          "금호4가동",
          "옥수동",
          "성수1가동",
          "성수2가동",
          "송정동",
          "용답동",
        ],
      },
      gwangjin: {
        name: "광진구",
        neighborhoods: [
          "중곡동",
          "능동",
          "광장동",
          "자양동",
          "화양동",
          "군자동",
        ],
      },
      dongdaemun: {
        name: "동대문구",
        neighborhoods: [
          "용신동",
          "제기동",
          "전농동",
          "답십리동",
          "장안동",
          "청량리동",
          "회기동",
          "휘경동",
          "이문동",
        ],
      },
      jungnang: {
        name: "중랑구",
        neighborhoods: [
          "면목동",
          "상봉동",
          "중화동",
          "묵동",
          "망우동",
          "신내동",
        ],
      },
      seongbuk: {
        name: "성북구",
        neighborhoods: [
          "성북동",
          "삼선동",
          "동선동",
          "돈암동",
          "안암동",
          "보문동",
          "정릉동",
          "길음동",
          "종암동",
          "월곡동",
          "장위동",
          "석관동",
        ],
      },
      gangbuk: {
        name: "강북구",
        neighborhoods: [
          "삼양동",
          "미아동",
          "송중동",
          "송천동",
          "삼각산동",
          "번동",
          "수유동",
          "우이동",
          "인수동",
        ],
      },
      dobong: {
        name: "도봉구",
        neighborhoods: ["쌍문동", "방학동", "창동", "도봉동"],
      },
      nowon: {
        name: "노원구",
        neighborhoods: ["월계동", "공릉동", "하계동", "중계동", "상계동"],
      },
      eunpyeong: {
        name: "은평구",
        neighborhoods: [
          "녹번동",
          "불광동",
          "갈현동",
          "구산동",
          "대조동",
          "응암동",
          "역촌동",
          "신사동",
          "증산동",
          "수색동",
          "진관동",
        ],
      },
      seodaemun: {
        name: "서대문구",
        neighborhoods: [
          "충현동",
          "천연동",
          "북아현동",
          "신촌동",
          "연희동",
          "홍제동",
          "홍은동",
          "남가좌동",
          "북가좌동",
        ],
      },
      mapo: {
        name: "마포구",
        neighborhoods: [
          "아현동",
          "공덕동",
          "도화동",
          "용강동",
          "대흥동",
          "염리동",
          "신수동",
          "서강동",
          "서교동",
          "합정동",
          "망원동",
          "연남동",
          "성산동",
          "상암동",
        ],
      },
      yangcheon: {
        name: "양천구",
        neighborhoods: ["목동", "신월동", "신정동"],
      },
      gangseo: {
        name: "강서구",
        neighborhoods: [
          "염창동",
          "등촌동",
          "화곡동",
          "가양동",
          "발산동",
          "공항동",
          "방화동",
        ],
      },
      guro: {
        name: "구로구",
        neighborhoods: [
          "신도림동",
          "구로동",
          "가리봉동",
          "고척동",
          "개봉동",
          "오류동",
          "항동",
        ],
      },
      geumcheon: {
        name: "금천구",
        neighborhoods: ["가산동", "독산동", "시흥동"],
      },
      yeongdeungpo: {
        name: "영등포구",
        neighborhoods: [
          "영등포본동",
          "영등포동",
          "여의동",
          "당산동",
          "도림동",
          "문래동",
          "양평동",
          "신길동",
          "대림동",
        ],
      },
      dongjak: {
        name: "동작구",
        neighborhoods: [
          "노량진동",
          "상도동",
          "흑석동",
          "사당동",
          "대방동",
          "신대방동",
        ],
      },
      gwanak: {
        name: "관악구",
        neighborhoods: [
          "보라매동",
          "청림동",
          "성현동",
          "행운동",
          "낙성대동",
          "청룡동",
          "은천동",
          "중앙동",
          "인헌동",
          "남현동",
          "서원동",
          "신원동",
          "서림동",
          "신사동",
          "신림동",
          "난향동",
          "조원동",
          "대학동",
          "미성동",
          "난곡동",
        ],
      },
      seocho: {
        name: "서초구",
        neighborhoods: ["서초동", "잠원동", "반포동", "방배동"],
      },
      gangnam: {
        name: "강남구",
        neighborhoods: [
          "신사동",
          "논현동",
          "압구정동",
          "청담동",
          "삼성동",
          "대치동",
          "역삼동",
          "도곡동",
          "개포동",
          "일원동",
          "수서동",
        ],
      },
      songpa: {
        name: "송파구",
        neighborhoods: [
          "풍납동",
          "거여동",
          "마천동",
          "방이동",
          "오륜동",
          "오금동",
          "송파동",
          "석촌동",
          "삼전동",
          "가락동",
          "문정동",
          "장지동",
          "위례동",
        ],
      },
      gangdong: {
        name: "강동구",
        neighborhoods: [
          "강일동",
          "상일동",
          "명일동",
          "고덕동",
          "암사동",
          "천호동",
          "길동",
          "둔촌동",
        ],
      },
    },
  },
  incheon: {
    name: "인천광역시",
    districts: {
      jung: {
        name: "중구",
        neighborhoods: [
          "중앙동1가",
          "중앙동2가",
          "중앙동3가",
          "중앙동4가",
          "해안동1가",
          "해안동2가",
          "해안동3가",
          "해안동4가",
          "관동1가",
          "관동2가",
          "관동3가",
          "송학동1가",
          "송학동2가",
          "송학동3가",
          "사동",
          "신생동",
          "답동",
          "신포동",
          "항동1가",
          "항동2가",
          "항동3가",
          "항동4가",
          "항동5가",
          "항동6가",
          "항동7가",
        ],
      },
      dong: {
        name: "동구",
        neighborhoods: [
          "왕길동",
          "도화동",
          "만석동",
          "송현동",
          "광영동",
          "천하동",
          "연안동",
        ],
      },
      michuhol: {
        name: "미추홀구",
        neighborhoods: [
          "중산동",
          "신포동",
          "용현동",
          "신흥동",
          "도화동",
          "문학동",
          "송현동",
        ],
      },
      yeonsu: {
        name: "연수구",
        neighborhoods: [
          "옥련동",
          "선학동",
          "연수동",
          "청학동",
          "동춘동",
          "송도동",
        ],
      },
      namdong: {
        name: "남동구",
        neighborhoods: [
          "구월동",
          "간석동",
          "만수동",
          "장수동",
          "운연동",
          "서창동",
          "남촌동",
          "수산동",
          "도림동",
          "논현동",
          "고잔동",
        ],
      },
      bupyeong: {
        name: "부평구",
        neighborhoods: [
          "갈산동",
          "구산동",
          "부개동",
          "부평동",
          "산곡동",
          "삼산동",
          "십정동",
          "일신동",
          "청천동",
        ],
      },
      gyeyang: {
        name: "계양구",
        neighborhoods: [
          "갈현동",
          "계산동",
          "귤현동",
          "노오지동",
          "다남동",
          "동양동",
          "둑실동",
          "목상동",
          "박촌동",
          "방축동",
          "병방동",
          "상야동",
          "서운동",
          "선주지동",
          "오류동",
          "용종동",
          "이화동",
          "임학동",
          "작전동",
          "장기동",
          "평동",
          "하야동",
          "효성동",
        ],
      },
      seo: {
        name: "서구",
        neighborhoods: [
          "가정동",
          "가좌동",
          "검암동",
          "경서동",
          "공촌동",
          "금곡동",
          "당하동",
          "대곡동",
          "마전동",
          "백석동",
          "불로동",
          "석남동",
          "시천동",
          "신현동",
          "심곡동",
          "연희동",
          "오류동",
          "왕길동",
          "원당동",
          "원창동",
          "청라동",
        ],
      },
      ganghwa: {
        name: "강화군",
        neighborhoods: [
          "강화읍",
          "선원면",
          "불은면",
          "길상면",
          "화도면",
          "양도면",
          "교동면",
          "삼산면",
          "서도면",
        ],
      },
      ongjin: {
        name: "옹진군",
        neighborhoods: [
          "옹진읍",
          "북도면",
          "백령면",
          "대청면",
          "덕적면",
          "영흥면",
          "자월면",
          "연평면",
        ],
      },
    },
  },
  gyeonggi: {
    name: "경기도",
    districts: {
      suwon: {
        name: "수원시",
        neighborhoods: ["장안구", "권선구", "팔달구", "영통구"],
      },
      seongnam: {
        name: "성남시",
        neighborhoods: ["수정구", "중원구", "분당구"],
      },
      uijeongbu: {
        name: "의정부시",
        neighborhoods: [
          "가능동",
          "흥선동",
          "의정부1동",
          "의정부2동",
          "의정부3동",
          "호원1동",
          "호원2동",
          "장암동",
          "신곡1동",
          "신곡2동",
          "송산1동",
          "송산2동",
          "송산3동",
        ],
      },
      anyang: { name: "안양시", neighborhoods: ["만안구", "동안구"] },
      bucheon: {
        name: "부천시",
        neighborhoods: [
          "중동",
          "상동",
          "심곡동",
          "송내동",
          "소사본동",
          "역곡동",
          "오정동",
          "신중동",
          "범안동",
          "대산동",
        ],
      },
      gwangmyeong: {
        name: "광명시",
        neighborhoods: [
          "광명1동",
          "광명2동",
          "광명3동",
          "광명4동",
          "광명5동",
          "광명6동",
          "광명7동",
          "철산1동",
          "철산2동",
          "철산3동",
          "철산4동",
          "하안1동",
          "하안2동",
          "하안3동",
          "하안4동",
          "소하1동",
          "소하2동",
          "학온동",
        ],
      },
      pyeongtaek: {
        name: "평택시",
        neighborhoods: [
          "팽성읍",
          "안중읍",
          "포승읍",
          "청북읍",
          "진위면",
          "서탄면",
          "고덕면",
          "오성면",
          "현덕면",
          "중앙동",
          "서정동",
          "송탄동",
          "신장동",
          "지산동",
          "송북동",
          "신평동",
          "원평동",
          "비전1동",
          "비전2동",
        ],
      },
      dongducheon: {
        name: "동두천시",
        neighborhoods: [
          "생연1동",
          "생연2동",
          "중앙동",
          "보산동",
          "불현동",
          "송내동",
          "소요동",
        ],
      },
      ansan: { name: "안산시", neighborhoods: ["상록구", "단원구"] },
      goyang: {
        name: "고양시",
        neighborhoods: ["덕양구", "일산동구", "일산서구"],
      },
      gwacheon: {
        name: "과천시",
        neighborhoods: [
          "중앙동",
          "갈현동",
          "별양동",
          "부림동",
          "과천동",
          "문원동",
        ],
      },
      guri: {
        name: "구리시",
        neighborhoods: [
          "갈매동",
          "동구동",
          "인창동",
          "교문1동",
          "교문2동",
          "수택1동",
          "수택2동",
          "수택3동",
        ],
      },
      namyangju: {
        name: "남양주시",
        neighborhoods: [
          "와부읍",
          "진접읍",
          "진건읍",
          "오남읍",
          "별내읍",
          "화도읍",
          "퇴계원읍",
          "조안면",
          "금곡동",
          "양정동",
          "다산1동",
          "다산2동",
          "별내동",
        ],
      },
      osan: {
        name: "오산시",
        neighborhoods: [
          "중앙동",
          "대원동",
          "남촌동",
          "신장동",
          "세마동",
          "초평동",
        ],
      },
      siheung: {
        name: "시흥시",
        neighborhoods: [
          "대야동",
          "신천동",
          "은행동",
          "매화동",
          "목감동",
          "신현동",
          "능곡동",
          "장곡동",
          "정왕본동",
          "정왕1동",
          "정왕2동",
          "정왕3동",
          "정왕4동",
        ],
      },
      gunpo: {
        name: "군포시",
        neighborhoods: [
          "군포1동",
          "군포2동",
          "산본1동",
          "산본2동",
          "금정동",
          "재궁동",
          "오금동",
          "수리동",
          "궁내동",
          "대야동",
          "광정동",
          "송부동",
        ],
      },
      uiwang: {
        name: "의왕시",
        neighborhoods: ["고천동", "부곡동", "오전동", "내손동"],
      },
      hanam: {
        name: "하남시",
        neighborhoods: ["천현동", "신장동", "덕풍동", "미사동", "위례동"],
      },
      yongin: { name: "용인시", neighborhoods: ["처인구", "기흥구", "수지구"] },
      icheon: {
        name: "이천시",
        neighborhoods: [
          "장호원읍",
          "부발읍",
          "신둔면",
          "백사면",
          "호법면",
          "마장면",
          "대월면",
          "모가면",
          "설성면",
          "율면",
          "창전동",
          "중리동",
          "관고동",
          "증포동",
        ],
      },
      anseong: {
        name: "안성시",
        neighborhoods: [
          "공도읍",
          "보개면",
          "금광면",
          "서운면",
          "미양면",
          "대덕면",
          "양성면",
          "원곡면",
          "일죽면",
          "죽산면",
          "삼죽면",
          "고삼면",
          "안성동",
          "원곡동",
          "봉산동",
          "도기동",
          "성남동",
          "동본동",
          "인지동",
          "금석동",
          "연지동",
          "대천동",
          "서인동",
          "석정동",
          "아양동",
          "옥산동",
          "인지동",
          "금석동",
          "연지동",
          "대천동",
          "서인동",
          "석정동",
          "아양동",
          "옥산동",
        ],
      },
      pocheon: {
        name: "포천시",
        neighborhoods: [
          "소흘읍",
          "군내면",
          "내촌면",
          "가산면",
          "신북면",
          "창수면",
          "영중면",
          "일동면",
          "이동면",
          "영북면",
          "관인면",
          "화현면",
          "포천동",
          "선단동",
        ],
      },
      yeoju: {
        name: "여주시",
        neighborhoods: [
          "가남읍",
          "점동면",
          "능서면",
          "흥천면",
          "금사면",
          "산북면",
          "대신면",
          "북내면",
          "강천면",
          "여주동",
          "중앙동",
          "오학동",
        ],
      },
      yangpyeong: {
        name: "양평군",
        neighborhoods: [
          "양평읍",
          "강상면",
          "강하면",
          "양서면",
          "옥천면",
          "서종면",
          "단월면",
          "청운면",
          "양동면",
          "지평면",
          "용문면",
          "개군면",
        ],
      },
      gapyeong: {
        name: "가평군",
        neighborhoods: ["가평읍", "설악면", "청평면", "상면", "조종면", "북면"],
      },
      yeoncheon: {
        name: "연천군",
        neighborhoods: [
          "연천읍",
          "전곡읍",
          "군남면",
          "청산면",
          "백학면",
          "미산면",
          "왕징면",
          "신서면",
          "중면",
          "장남면",
        ],
      },
    },
  },
};

export const getRegionNames = (sidoId, sigunguId, neighborhoodId) => {
  const sidoName = regionData[sidoId]?.name
  const sigunguName = regionData[sidoId]?.districts?.[sigunguId]?.name
  
  // 읍면동 이름을 찾을 때 neighborhoodId가 인덱스인지 문자열인지 확인
  let neighborhoodName = null
  
  if (sidoId && sigunguId && neighborhoodId !== undefined) {
    const neighborhoods = regionData[sidoId]?.districts?.[sigunguId]?.neighborhoods
    if (neighborhoods) {
      // neighborhoodId가 숫자인 경우 (인덱스)
      if (typeof neighborhoodId === 'number' || !isNaN(neighborhoodId)) {
        const index = parseInt(neighborhoodId)
        neighborhoodName = neighborhoods[index]
      } else {
        // neighborhoodId가 문자열인 경우 (직접 매칭)
        neighborhoodName = neighborhoods.find(n => n === neighborhoodId) || neighborhoods[neighborhoodId]
      }
    }
  }
  
  return { sidoName, sigunguName, neighborhoodName }
}

export const isRegionSelectionComplete = (sidoId, sigunguId, neighborhoodId) => {
  const { sidoName, sigunguName, neighborhoodName } = getRegionNames(sidoId, sigunguId, neighborhoodId)
  return !!(sidoName && sigunguName && neighborhoodName)
}
